# Install base
FROM python:3.11.7-slim-bullseye

# Set a workdir
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy the rest of the code
COPY . .

# Run the app
CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]

# To build: docker build -f Dockerfile.dev .
# To run: docker run -p 8000:8000 -v $(pwd):/app <img_id>