# Generated by Django 5.0 on 2023-12-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalworkouts',
            name='workout_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
