# Generated by Django 5.0 on 2023-12-13 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_api', '0002_alter_personalworkouts_workout_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalworkouts',
            name='rpe',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
