# Generated by Django 5.0 on 2023-12-13 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_api', '0003_alter_personalworkouts_rpe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musclesexercised',
            name='exercise_name',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='personalworkouts',
            name='exercise_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fitness_api.musclesexercised'),
        ),
    ]
