# Generated by Django 5.0 on 2023-12-14 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_api', '0004_alter_musclesexercised_exercise_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musclesexercised',
            name='exercise_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='personalworkouts',
            name='exercise_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_api.musclesexercised'),
        ),
    ]
