# Generated by Django 3.0.8 on 2023-12-21 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitness_api', '0006_auto_20231221_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalworkouts',
            name='exercise_name',
        ),
        migrations.AddField(
            model_name='personalworkouts',
            name='oneRM',
            field=models.FloatField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalworkouts',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personalworkouts',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='personalworkouts',
            name='distance',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='personalworkouts',
            name='duration',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='personalworkouts',
            name='notes',
            field=models.CharField(blank=True, default=None, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personalworkouts',
            name='reps',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='personalworkouts',
            name='rpe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalworkouts',
            name='seconds',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='personalworkouts',
            name='set_order',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='personalworkouts',
            name='weight',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='personalworkouts',
            name='workout_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='personalworkouts',
            name='workout_notes',
            field=models.CharField(blank=True, default=None, max_length=256),
            preserve_default=False,
        ),
    ]
