# Generated by Django 3.0.8 on 2023-12-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_api', '0007_auto_20231221_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalworkouts',
            name='exercise_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
