# Generated by Django 3.0.8 on 2023-12-21 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_api', '0008_personalworkouts_exercise_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalworkouts',
            name='oneRM',
        ),
    ]
